// ============================================================
//  js/data.js — AUTO-GENERATED by build.py
//  Last built: 2026-03-23 10:54
//  CDN: https://cdn.jsdelivr.net/gh/yiming-zhu-98/yiming-zhu-98.github.io@zym
//
//  ⚠  DO NOT edit this file directly.
//     • Edit posts in:       posts/research/*.md
//                            posts/blogs/*.md
//     • Edit CDN settings:   build.py (top of file)
//     • Edit personal info:  js/config.js
//     • Then run:            python build.py
// ============================================================

// Append posts to the SITE_DATA object already created by config.js
window.SITE_DATA.research = [
  {
    id:         "research-3",
    emoji:      "",
    image:      "https://cdn.jsdelivr.net/gh/yiming-zhu-98/yiming-zhu-98.github.io@zym/images/research/GOAE.png",
    date:       "2023-03-15",
    title:      "Make Encoder Great Again in 3D GAN Inversion through Geometry and Occlusion-Aware Encoding",
    title_zh:   "\u901a\u8fc7\u51e0\u4f55\u4e0e\u906e\u6321\u611f\u77e5\u6784\u5efa3D GAN\u53cd\u6f14\u7f16\u7801\u5668",
    excerpt:    "ICCV2023",
    excerpt_zh: "ICCV2023",
    content: `
# [Make Encoder Great Again in 3D GAN Inversion through Geometry and Occlusion-Aware Encoding](https://eg3d-goae.github.io/)

## Abstract

This is an **open-source** work which achieves high reconstruction fidelity and reasonable 3D geometry simultaneously from a single image input. Our work could be aplied in Novel View Synthesis, 3D-Consistent Editing. 

## Methodology

Our framework could be divided into two parts. 
- W space inversion.  We design an encoder E to invert input image I into w+ latent codes
- Complement the F space. We calculate the image residual △I between the input image and its reconstruction and propose AFA module to refine the F latent maps.

## [Project WebPage 🔗](https://eg3d-goae.github.io/)
    `,
    content_zh: `
# 通过几何与遮挡感知构建3D GAN反演编码器

## 摘要

这是一项**开源**工作，它仅需单张图像输入即可同时实现高保真度的重建和合理的3D几何形状。我们的工作可应用于新视角合成和3D一致性编辑。

## 方法论

我们的框架可以分为两部分：

- W 空间反转。我们设计了一个编码器 E，将输入图像 I 反转为 w+ 个潜在编码。

- F 空间补全。我们计算输入图像与其重建图像之间的图像残差 △I，并提出 AFA 模块来优化 F 潜在映射。

## [项目主页 🔗](https://eg3d-goae.github.io/)
    `
  },

  {
    id:         "research-5",
    emoji:      "",
    image:      "https://cdn.jsdelivr.net/gh/yiming-zhu-98/yiming-zhu-98.github.io@zym/images/research/ffclip.png",
    date:       "2023-01-03",
    title:      "One Model to Edit Them All:Free-Form Text-Driven Image Manipulation with Semantic Modulations",
    title_zh:   "\u4e00\u7edf\u5929\u4e0b\u7684\u6a21\u578b:\u57fa\u4e8e\u8bed\u4e49\u8c03\u5236\u652f\u6301\u81ea\u7531\u6587\u672c\u8f93\u5165\u7684\u56fe\u50cf\u7f16\u8f91",
    excerpt:    "NeurIPS2022 (Spotlight)",
    excerpt_zh: "NeurIPS2022 (Spotlight)",
    content: `
# [One Model to Edit Them All:Free-Form Text-Driven Image Manipulation with Semantic Modulations](https://arxiv.org/abs/2210.07883)

## Abstract

We propose FFCLIP to support Free-form text prompts for image manipulation. We are the **first** method to achieve all semantic editing using a single model.

## Methodology
- Semantic Alignment Module. The semantic alignment performs the automatic latent mapping via linear transformations with a cross attention mechanism.
- Semantic Injection Module. We inject semantics from text prompt embeddings to the StyleGAN latent space. 

## [Project WebPage 🔗](https://github.com/kristen-rang/FFCLIP)
    `,
    content_zh: `
# [一统天下的模型:基于语义调制支持自由文本输入的图像编辑](https://arxiv.org/abs/2210.07883)

## 摘要
我们提出 FFCLIP，旨在支持图像操作的自由文本提示。我们是**首个**使用单一模型实现所有语义编辑的方法。

## 方法论
- 语义对齐模块。语义对齐模块通过线性变换和交叉注意力机制实现自动潜在映射。

- 语义注入模块。我们将文本提示嵌入中的语义信息注入到 StyleGAN 的潜在空间中。

## [项目主页 🔗](https://github.com/kristen-rang/FFCLIP)
    `
  },

  {
    id:         "research-2",
    emoji:      "",
    image:      "https://cdn.jsdelivr.net/gh/yiming-zhu-98/yiming-zhu-98.github.io@zym/images/research/dynamixer.jpg",
    date:       "2022-12-15",
    title:      "DynaMixer:A Vision MLP Architecture with Dynamic Mixing",
    title_zh:   "DynaMixer:\u5177\u6709\u52a8\u6001\u7f16\u7801\u529f\u80fd\u7684 Vision MLP \u67b6\u6784",
    excerpt:    "ICML2022",
    excerpt_zh: "ICML2022",
    content: `
# [DynaMixer:A Vision MLP Architecture with Dynamic Mixing](https://arxiv.org/pdf/2201.12083)

## Abstract

This work proposes a pure **MLP architecture** that rivals the attention mechanism from a mathematical perspective, achieving optimal performance with the same parameters.

## Methodology
\`\`\`python
Algorithm 1 Pseudo-code for DynaMixer Block (PyTorchlike)
###### initializaiton #######
proj_c = nn.Linear(D, D)
proj_o = nn.Linear(D, D)
###### code in forward ######
def dyna_mixer_block(self, X):
    H, W, D = X.shape
    # row mixing
    for h = 1:H
        Y_h[h,:,:] = DynaMixerOp_h(X[h,:,:])
    # column mixing
    for w = 1:W
        Y_w[:,w,:] = DynaMixerOp_w(X[:,w,:])
    # channel mixing
    Y_c = proj_c(X)
    Y_out = Y_h + Y_w + Y_c
    return proj_o(Y_out)
\`\`\`

## [Project WebPage 🔗](https://github.com/ziyuwwang/DynaMixer)
    `,
    content_zh: `
# DynaMixer:具有动态编码功能的 Vision MLP 架构

## 摘要

这项工作提出了一种纯粹的**MLP架构**，从数学角度来看，它能够与注意力机制相媲美，并在相同的参数下实现最佳性能。

## 方法论

\`\`\`python
算法 1 DynaMixer Block的伪代码   (PyTorch风格)
###### 初始化投影矩阵 #######
proj_c = nn.Linear(D, D)
proj_o = nn.Linear(D, D)
###### forward函数代码 ######
def dyna_mixer_block(self, X):
    H, W, D = X.shape
    # row mixing
    for h = 1:H
        Y_h[h,:,:] = DynaMixerOp_h(X[h,:,:])
    # column mixing
    for w = 1:W
        Y_w[:,w,:] = DynaMixerOp_w(X[:,w,:])
    # channel mixing
    Y_c = proj_c(X)
    Y_out = Y_h + Y_w + Y_c
    return proj_o(Y_out)
\`\`\`

## [项目主页 🔗](https://github.com/ziyuwwang/DynaMixer)
    `
  },

  {
    id:         "research-4",
    emoji:      "",
    image:      "https://cdn.jsdelivr.net/gh/yiming-zhu-98/yiming-zhu-98.github.io@zym/images/research/flowfill.jpg",
    date:       "2022-06-03",
    title:      "Diverse Image Inpainting with Normalizing Flow",
    title_zh:   "\u57fa\u4e8e\u6d41\u6a21\u578b\u7b49\u591a\u6837\u6027\u56fe\u7247\u8865\u5168",
    excerpt:    "ECCV2022",
    excerpt_zh: "ECCV2022",
    content: `
# [Diverse Image Inpainting with Normalizing Flow](https://www.ecva.net/papers/eccv_2022/papers_ECCV/papers/136830053.pdf)

## Abstract

We propose Flow-Fill an inpainting framework that utilizes a conditional normalizing flow model to generate diverse structural priors. Flow-Fill achieves a real-time inference speed that is approximately **87 times** faster than autoregressive-based models and **142 times** faster than diffusion-based models.

## Methodology
- Learn Structural Priors. We use a conditional normalizing flow to model diverse structural priors.
- Guided Texture Generation. The structural priors obtained in the first stage are low-resolution and have no texture details. In the second stage, we upsample the image and generate texture.

## [Project WebPage 🔗](https://www.ecva.net/papers/eccv_2022/papers_ECCV/papers/136830053.pdf)
    `,
    content_zh: `
# [基于流模型等多样性图片补全](https://www.ecva.net/papers/eccv_2022/papers_ECCV/papers/136830053.pdf)

## 摘要
我们提出了一种名为 Flow-Fill 的图像修复框架，它利用条件归一化流模型生成多样化的结构先验。Flow-Fill 的实时推理速度比基于自回归的模型快约 **87 倍**，比基于扩散的模型快约 **142 倍**。

## 方法论

- 学习结构先验。我们使用条件归一化流来建模不同的结构先验。

- 引导纹理生成。第一阶段获得的结构先验分辨率较低，缺乏纹理细节。在第二阶段，我们对图像进行上采样并生成纹理。

## [项目主页 🔗](https://www.ecva.net/papers/eccv_2022/papers_ECCV/papers/136830053.pdf)
    `
  },

  {
    id:         "research-1",
    emoji:      "",
    image:      "https://cdn.jsdelivr.net/gh/yiming-zhu-98/yiming-zhu-98.github.io@zym/images/research/hfflow.jpg",
    date:       "2022-01-15",
    title:      "High-Frequency Normalizing Flow for Image Rescaling",
    title_zh:   "\u9ad8\u9891\u6d41\u51fd\u6570\u89e3\u51b3\u56fe\u50cf\u7f29\u653e\u53d8\u6362",
    excerpt:    "IEEE Transactions on Image Processing",
    excerpt_zh: "IEEE Transactions on Image Processing",
    content: `
# [High-Frequency Normalizing Flow for Image Rescaling](https://ieeexplore.ieee.org/document/9826354)

## Abstract

This work propose an overall invertible framework with a conditional flow on the high-frequency space for High-quality image compression and restoration. 

## Methodology
We introduce a reference low-resolution (LR) manifold and propose a crossentropy Gaussian loss (CGloss) to force the downscaled manifold closer to the reference LR manifold and simultaneously fulfill recovering missing details. HfFlow can be generalized to other scale transformation tasks such as image colorization with its excellent rescaling capacity.

## [Project WebPage 🔗](https://ieeexplore.ieee.org/document/9826354)
    `,
    content_zh: `
# 高频流函数解决图像缩放变换

## 摘要

本文提出了一种基于高频空间条件流的整体可逆框架，用于高质量图像压缩和恢复。

## 方法论
我们引入了一个参考低分辨率（LR）流形，并提出了一种交叉熵高斯损失函数（CGloss），以促使降尺度后的流形更接近参考LR流形，同时恢复缺失的细节。凭借其出色的重缩放能力，HfFlow可以推广到其他尺度变换任务，例如图像着色。

## [项目主页 🔗](https://ieeexplore.ieee.org/document/9826354)
    `
  },

  {
    id:         "research-6",
    emoji:      "",
    image:      "https://cdn.jsdelivr.net/gh/yiming-zhu-98/yiming-zhu-98.github.io@zym/images/research/SJLT.jpg",
    date:       "2021-12-03",
    title:      "Weakly Supervised Instance Segmentation By Exploring Entire Object Regions",
    title_zh:   "\u901a\u8fc7\u63a2\u7d22\u6574\u4e2a\u5bf9\u8c61\u533a\u57df\u8fdb\u884c\u5f31\u76d1\u7763\u5b9e\u4f8b\u5206\u5272",
    excerpt:    "IEEE Transactions on Multimedia",
    excerpt_zh: "IEEE Transactions on Multimedia",
    content: `
# [Weakly Supervised Instance Segmentation By Exploring Entire Object Regions](https://ieeexplore.ieee.org/abstract/document/9612036)

## Abstract

We propose a novel self-supervised joint learning framework and consider the clustering problem as calculating the probability that pixels belong to each instance.

## Methodology
- In the first stream, we leverage a joint learning framework to implement image-level supervised semantic segmentation with self-supervised saliency detection.
- In the second stream, we propose a Center Detection Network to detect different instances’ centers with the gaussian loss function to cluster instances pixels. 
- Besides, an integration module is utilized to combine information of both streams and get precise pseudo instances labels. 

## [Project WebPage 🔗](https://ieeexplore.ieee.org/abstract/document/9612036)
    `,
    content_zh: `
# [通过探索整个对象区域进行弱监督实例分割](https://ieeexplore.ieee.org/abstract/document/9612036)

## 摘要
我们提出了一种新颖的自监督联合学习框架，并将聚类问题视为计算像素属于每个实例的概率。

## 方法论
- 在第一个流程中，我们利用联合学习框架实现图像级监督语义分割和自监督显著性检测。

- 在第二个流程中，我们提出了一种中心检测网络，利用高斯损失函数检测不同实例的中心，从而对实例像素进行聚类。

- 此外，我们还使用了一个集成模块来融合两个流程的信息，以获得精确的伪实例标签。

## [项目主页 🔗](https://ieeexplore.ieee.org/abstract/document/9612036)
    `
  }
];

window.SITE_DATA.blogs = [

];
