#!/usr/bin/env python3
"""
build.py — Cosmos site builder
================================
Reads all .md files from posts/research/ and posts/blogs/,
then generates js/data.js which ONLY contains the posts arrays.
Personal info (i18n + about) lives in js/config.js — edit that directly.

USAGE:
    python build.py

Run this every time you add or edit a post, then:
    git add .
    git commit -m "update posts"
    git push

MARKDOWN FILE FORMAT:
    ---
    id: blog-2025-04
    emoji: 🚀
    image: ""
    date: 2025-04-01
    title: My English Title
    title_zh: 我的中文标题
    excerpt: Short English summary for the card.
    excerpt_zh: 显示在卡片上的中文摘要。
    ---

    # English content (Markdown)

    ---zh---

    # 中文内容（Markdown）
"""

import os, re, json
from pathlib import Path
from datetime import datetime

ROOT         = Path(__file__).parent
RESEARCH_DIR = ROOT / "posts" / "research"
BLOGS_DIR    = ROOT / "posts" / "blogs"
OUTPUT       = ROOT / "js" / "data.js"


def parse_md(filepath: Path) -> dict:
    text = filepath.read_text(encoding="utf-8")
    fm_match = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.DOTALL)
    if not fm_match:
        raise ValueError(f"No front matter found in {filepath.name}")
    fm_text = fm_match.group(1)
    body    = text[fm_match.end():]

    meta = {}
    for line in fm_text.splitlines():
        m = re.match(r'^(\w+)\s*:\s*(.*)', line)
        if m:
            key, val = m.group(1), m.group(2).strip()
            if (val.startswith('"') and val.endswith('"')) or \
               (val.startswith("'") and val.endswith("'")):
                val = val[1:-1]
            meta[key] = val

    en_body, zh_body = (body.split("---zh---", 1) + [""])[:2]

    for field in ["id", "date", "title", "title_zh", "excerpt", "excerpt_zh"]:
        if field not in meta:
            raise ValueError(f"Missing '{field}' in {filepath.name}")

    return {
        "id":         meta["id"],
        "emoji":      meta.get("emoji", "📄"),
        "image":      meta.get("image", ""),
        "date":       meta["date"],
        "title":      meta["title"],
        "title_zh":   meta["title_zh"],
        "excerpt":    meta["excerpt"],
        "excerpt_zh": meta["excerpt_zh"],
        "content":    en_body.strip(),
        "content_zh": zh_body.strip(),
    }


def load_posts(directory: Path) -> list:
    if not directory.exists():
        print(f"  ⚠  Not found: {directory}")
        return []
    posts = []
    for md_file in sorted(directory.glob("*.md")):
        try:
            posts.append(parse_md(md_file))
            print(f"  ✓  {md_file.name}")
        except Exception as e:
            print(f"  ✗  {md_file.name}: {e}")
    posts.sort(key=lambda p: p["date"], reverse=True)
    return posts


def js_str(s: str) -> str:
    return s.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")


def post_to_js(post: dict) -> str:
    lines = [
        "  {",
        f'    id:         {json.dumps(post["id"])},',
        f'    emoji:      {json.dumps(post["emoji"])},',
        f'    image:      {json.dumps(post["image"])},',
        f'    date:       {json.dumps(post["date"])},',
        f'    title:      {json.dumps(post["title"])},',
        f'    title_zh:   {json.dumps(post["title_zh"])},',
        f'    excerpt:    {json.dumps(post["excerpt"])},',
        f'    excerpt_zh: {json.dumps(post["excerpt_zh"])},',
        f'    content: `\n{js_str(post["content"])}\n    `,',
        f'    content_zh: `\n{js_str(post["content_zh"])}\n    `',
        "  }",
    ]
    return "\n".join(lines)


def build():
    print("\n🚀 Cosmos site builder")
    print("=" * 40)

    print("\nLoading research posts...")
    research = load_posts(RESEARCH_DIR)

    print("\nLoading blog posts...")
    blogs = load_posts(BLOGS_DIR)

    print(f"\nTotal: {len(research)} research, {len(blogs)} blogs")

    research_js = ",\n\n".join(post_to_js(p) for p in research)
    blogs_js    = ",\n\n".join(post_to_js(p) for p in blogs)

    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    output = f"""// ============================================================
//  js/data.js — AUTO-GENERATED by build.py
//  Last built: {now}
//
//  ⚠  DO NOT edit this file directly.
//     • Edit posts in:       posts/research/*.md
//                            posts/blogs/*.md
//     • Edit personal info:  js/config.js
//     • Then run:            python build.py
// ============================================================

// Append posts to the SITE_DATA object already created by config.js
window.SITE_DATA.research = [
{research_js}
];

window.SITE_DATA.blogs = [
{blogs_js}
];
"""

    OUTPUT.write_text(output, encoding="utf-8")
    print(f"\n✅ Written to {OUTPUT}")
    print("\nNext steps:")
    print("  git add .")
    print('  git commit -m "update posts"')
    print("  git push\n")


if __name__ == "__main__":
    build()